### ISSUE TITLE
[v2.1.0] com.unity.test-framework should be an optional dependency, not a hard one

### ISSUE THREAD

**Issue by thor-shuang** [hatayama/uLoopMCP#1061]
## Summary

In `Packages/src/package.json` for v2.1.0, `com.unity.test-framework` was added as a hard dependency. This breaks compilation for Unity environments where the Test Framework package is not installed (or cannot be installed) — for example, custom-built Unity Editors used by some studios.

In v1.6.3 the package did not declare a hard dependency on `com.unity.test-framework`, which made it possible (with light local stubbing) to use uLoopMCP in such environments.

## Environment

- Unity 2022.3 (custom in-house Editor build, no `com.unity.test-framework` available)
- uloop-cli: v2.1.0
- Package: io.github.hatayama.uloopmcp v2.1.0

## Reproduction

1. Use a Unity 2022.3 environment that does not have `com.unity.test-framework` installed (or where Test Framework itself cannot compile, e.g. some custom Editor builds).
2. Install uLoopMCP v2.1.0 as an embedded package.
3. Trigger a domain reload / compile.

## Expected behaviour

uLoopMCP package compiles cleanly. The `run-tests` tool can either be unavailable or return a clear "unsupported" message at runtime, but the rest of the package (compile, get-logs, execute-dynamic-code, find-game-objects, screenshot, control-play-mode, simulate-keyboard, simulate-mouse-input/ui, record-input/replay-input, …) keeps working.

## Actual behaviour

Compilation fails with around 30+ `error CS0246` errors across these files:

- `Editor/Api/McpTools/RunTests/RunTestsSchema.cs`
- `Editor/Api/McpTools/RunTests/RunTestsTool.cs`
- `Editor/Api/McpTools/RunTests/RunTestsResponse.cs`
- `Editor/Api/McpTools/UseCases/Tools/RunTestsUseCase.cs`
- `Editor/Core/ApplicationServices/TestExecutionService.cs`
- `Editor/Core/ApplicationServices/TestExecutionStateValidationService.cs`
- `Editor/Core/ApplicationServices/TestFilterCreationService.cs`
- `Editor/Core/CoreTools/TestRunner/PlayModeTestExecuter.cs`
- `Editor/Core/CoreTools/TestRunner/NUnitXmlResultExporter.cs`
- `Editor/Core/CoreTools/TestRunner/SerializableTestResult.cs`
- `Editor/Core/CoreTools/TestRunner/TestExecutionFilter.cs`

Missing types include `ITestResultAdaptor`, `TestStatus`, `TestMode`, `TestRunnerApi`, `ITestAdaptor`, `Filter`, `ICallbacks`, all from `UnityEditor.TestTools.TestRunner.Api`.

Because the `Editor` assembly fails to compile, the entire uLoopMCP server is broken — none of the other tools work either.

## Suggested fix

One of the following would unblock environments without Test Framework:

1. Remove `com.unity.test-framework` from `package.json` `dependencies` and gate every `using UnityEditor.TestTools.*` and every reference to test-framework types behind `#if UNITY_INCLUDE_TESTS` (the version define automatically defined by Unity when the test-framework package is present).
2. Or move all test-related code into a separate optional asmdef + define so the rest of the package compiles independently.

Either approach lets `run-tests` degrade gracefully (returning "Test Framework not available" at runtime) while preserving the rest of uLoopMCP's functionality.

## Workaround we are using locally

We maintain a local fork of v1.6.3 where the 6 Test-related .cs files are stubbed out and all `using UnityEditor.TestTools.*` lines are removed. This works on v1.6.3 because v1.6.3 did not declare a hard dependency on `com.unity.test-framework`. With v2.1.0 the workaround would also have to delete files and modify `SecuritySettings.cs` and `UnityToolRegistry.cs`, which makes every future upgrade a manual fork-merge job.

A first-class `#if UNITY_INCLUDE_TESTS` solution upstream would let custom-Unity environments stay on the latest uLoopMCP without forking.

Thanks for the great tool — uLoopMCP is the best Unity ↔ AI bridge we have found, and we would love to keep up with releases.

**Comment by hatayama** [comment]
Thank you for the report. I'll take care of it!

**Comment by hatayama** [comment]
https://github.com/hatayama/unity-cli-loop/pull/1062
I've fixed it and released version 2.1.1. Thanks for the report!
