### PR TITLE
fix: allow installation without Unity Test Framework

### LINKED ISSUE #1061: [v2.1.0] com.unity.test-framework should be an optional dependency, not a hard one
## Summary

In `Packages/src/package.json` for v2.1.0, `com.unity.test-framework` was added as a hard dependency. This breaks compilation for Unity environments where the Test Framework package is not installed (or cannot be installed) — for example, custom-built Unity Editors used by some studios.

In v1.6.3 the package did not declare a hard dependency on `com.unity.test-framework`, which made it possible (with light local stubbing) to use uLoopMCP in such environments.

## Environment

- Unity 2022.3 (custom in-house Editor build, no `com.unity.test-framework` available)
- uloop-cli: v2.1.0
- Package: io.github.hatayama.uloopmcp v2.1.0

## Reproduction

1. Use a Unity 2022.3 environment that does not have `com.unity.test-framework` installed (or where Test Framework itself cannot compile, e.g. some custom Editor builds).
2. Install uLoopMCP v2.1.0 as an embedded package.
3. Trigger a domain reload / compile.

## Expected behaviour

uLoopMCP package compiles cleanly. The `run-tests` tool can either be unavailable or return a clear "unsupported" message at runtime, but the rest of the package (compile, get-logs, execute-dynamic-code, find-game-objects, screenshot, control-play-mode, simulate-keyboard, simulate-mouse-input/ui, record-input/replay-input, …) keeps working.

## Actual behaviour

Compilation fails with around 30+ `error CS0246` errors across these files:

- `Editor/Api/McpTools/RunTests/RunTestsSchema.cs`
- `Editor/Api/McpTools/RunTests/RunTestsTool.cs`
- `Editor/Api/McpTools/RunTests/RunTestsResponse.cs`
- `Editor/Api/McpTools/UseCases/Tools/RunTestsUseCase.cs`
- `Editor/Core/ApplicationServices/TestExecutionService.cs`
- `Editor/Core/ApplicationServices/TestExecutionStateValidationService.cs`
- `Editor/Core/ApplicationServices/TestFilterCreationService.cs`
- `Editor/Core/CoreTools/TestRunner/PlayModeTestExecuter.cs`
- `Editor/Core/CoreTools/TestRunner/NUnitXmlResultExporter.cs`
- `Editor/Core/CoreTools/TestRunner/SerializableTestResult.cs`
- `Editor/Core/CoreTools/TestRunner/TestExecutionFilter.cs`

Missing types include `ITestResultAdaptor`, `TestStatus`, `TestMode`, `TestRunnerApi`, `ITestAdaptor`, `Filter`, `ICallbacks`, all from `UnityEditor.TestTools.TestRunner.Api`.

Because the `Editor` assembly fails to compile, the entire uLoopMCP server is broken — none of the other tools work either.

## Suggested fix

One of the following would unblock environments without Test Framework:

1. Remove `com.unity.test-framework` from `package.json` `dependencies` and gate every `using UnityEditor.TestTools.*` and every reference to test-framework types behind `#if UNITY_INCLUDE_TESTS` (the version define automatically defined by Unity when the test-framework package is present).
2. Or move all test-related code into a separate optional asmdef + define so the rest of the package compiles independently.

Either approach lets `run-tests` degrade gracefully (returning "Test Framework not available" at runtime) while preserving the rest of uLoopMCP's functionality.

## Workaround we are using locally

We maintain a local fork of v1.6.3 where the 6 Test-related .cs files are stubbed out and all `using UnityEditor.TestTools.*` lines are removed. This works on v1.6.3 because v1.6.3 did not declare a hard dependency on `com.unity.test-framework`. With v2.1.0 the workaround would also have to delete files and modify `SecuritySettings.cs` and `UnityToolRegistry.cs`, which makes every future upgrade a manual fork-merge job.

A first-class `#if UNITY_INCLUDE_TESTS` solution upstream would let custom-Unity environments stay on the latest uLoopMCP without forking.

Thanks for the great tool — uLoopMCP is the best Unity ↔ AI bridge we have found, and we would love to keep up with releases.

### PR DESCRIPTION
**Pull request by hatayama**
## Summary
- Unity projects can install uLoop without adding Unity Test Framework to their package dependencies.
- run-tests remains discoverable and returns a clear missing-dependency response when Test Framework is unavailable.
- The PR supply-chain audit now passes with refreshed TypeScript server dependency resolution.

## User Impact
- Before, projects without Unity Test Framework could fail to compile the package or see confusing run-tests behavior such as disabled-tool or command-not-found responses.
- After, the package installs without forcing Test Framework. Users can still invoke run-tests and get an actionable message explaining that Test Framework is required for test execution.
- Setup and settings version checks no longer choke on prerelease-style CLI versions.

## Changes
- Removed com.unity.test-framework from the distributable package dependency list and gated Test Runner integration behind ULOOPMCP_HAS_TEST_FRAMEWORK.
- Added fallback responses and availability checks so missing dependency errors are reported before disabled-tool handling.
- Kept run-tests in CLI tool metadata for projects without Test Framework.
- Added SemVer-aware CLI version comparison for editor setup/settings UI paths.
- Updated TypeScript server lockfile resolution for hono, express-rate-limit, and ip-address audit findings.
- Updated README, package README copies, skill guidance, and focused tests.

## Verification
- GitHub Actions for PR #1062: build-typescript-server, test-unity-package, README Sync Check, Security Code Scan, Unity Compile Check all passed.
- npx jest src/__tests__/package-metadata.test.ts --testTimeout=60000 --runInBand
- npm run lint
- npm run build
- node Packages/src/Cli~/dist/cli.bundle.cjs compile --project-path /Users/a12115/ghq/hatayama/unity-cli-loop2 --force-recompile false --wait-for-domain-reload true
- targeted EditMode run-tests checks for unavailable response, RunTestsUseCase validation, and TestExecutionStateValidationService behavior
- cd Packages/src/TypeScriptServer~ && npm ci --ignore-scripts=false
- cd Packages/src/TypeScriptServer~ && ULOOPMCP_PRODUCTION=true NODE_ENV=production npm run build:production
- cd Packages/src/TypeScriptServer~ && npx tsc --noEmit
- cd Packages/src/TypeScriptServer~ && npx knip
- cd Packages/src/TypeScriptServer~ && npm run security:check
- cd Packages/src/TypeScriptServer~ && npm audit --audit-level=moderate
- cd Packages/src/TypeScriptServer~ && npx lockfile-lint --path package-lock.json --type npm --allowed-hosts npm --allowed-schemes "https:" "git+https:"
- sh scripts/sync-readmes.sh --check
- git diff --check
- Codex review loop against origin/main: 0 valid findings

Closes #1061

## Overview

This PR makes the Unity Test Framework (`com.unity.test-framework`) an optional dependency for the uLoop MCP package, allowing projects to install and use uLoop without requiring the Test Framework. The `run-tests` tool remains discoverable in the CLI metadata but returns a clear unsupported response when the Test Framework is unavailable, while all other uLoop tools continue to function normally.

### Package Dependencies
- Removed `com.unity.test-framework` (v1.1.33) from `package.json` and `packages-lock.json`
- Pinned `hono` dependency to version 4.12.18 in TypeScript server `package.json` (audit fix)

### Conditional Compilation & Test Framework Gating
Introduced `ULOOPMCP_HAS_TEST_FRAMEWORK` preprocessor symbol to gate Test Framework integration:

- **RunTestsUseCase.cs**: Wrapped execution flow—when `ULOOPMCP_HAS_TEST_FRAMEWORK` is undefined, returns `RunTestsResponse` indicating unavailable framework; otherwise proceeds with validation and test execution
- **TestExecutionService.cs**: Both `ExecutePlayModeTestAsync` and `ExecuteEditModeTestAsync` conditionally compile; when unavailable, return early with `SerializableTestResult.CreateTestFrameworkUnavailable()`
- **PlayModeTestExecuter.cs** & **NUnitXmlResultExporter.cs**: Entire implementations wrapped in conditional compilation guards
- **SerializableTestResult.cs**: Test-result conversion logic and `ITestResultAdaptor` dependencies gated; added `CreateTestFrameworkUnavailable()` factory method

### Schema & Type Changes
- Introduced local `RunTestMode` enum in `RunTestsSchema.cs` (values: `EditMode = 1`, `PlayMode = 2`) to remove dependency on Unity's `TestMode` type
- Updated `TestExecutionStateValidationService.Validate()` signature from `TestMode` to `RunTestMode`
- Updated all test files and use cases to use `RunTestMode` instead of `TestMode`
- Removed import of `UnityEditor.TestTools.TestRunner.Api` from validation service

### Fallback Responses
- Added `RunTestsResponse.TestFrameworkUnavailableMessage` constant and `CreateTestFrameworkUnavailable()` factory method with `Success == false`, framework-unavailable message, zeroed test counts, and current UTC timestamp
- Added `SerializableTestResult.CreateTestFrameworkUnavailable()` for consistent internal serialization

### Tool Availability & Registration Logic
- Introduced `ToolExecutionAvailability` class with `ShouldReportDependencyUnavailableBeforeDisabled()` and `ShouldExposeInRegisteredTools()` methods that check test framework availability
- Updated `UnityToolRegistry.ExecuteToolAsync` to throw `ToolDisabledException` only when a tool is disabled AND not subject to dependency-unavailable bypass
- Updated `UnityToolRegistry.GetRegisteredTools()` to use `ToolExecutionAvailability.ShouldExposeInRegisteredTools()` for determining tool visibility
- `run-tests` now remains discoverable/exposed when disabled if the test framework is unavailable, so users receive a dependency-unavailable response instead of command-not-found

### CLI Version Comparison (SemVer-Aware)
- Added `CliVersionComparison` utility class supporting semantic versioning with pre-release parsing
  - `TryCompare(leftVersion, rightVersion, out comparison)`: Parses versions with optional `v` prefix, removes `+` build metadata, handles `-` pre-release tags, and compares using semantic rules
  - `IsSameVersion(leftVersion, rightVersion)`: Equality check delegating to comparison logic
- Updated `McpEditorWindow.CreateCliSetupData` to use `CliVersionComparison.TryCompare` instead of `System.Version` parsing
- Updated `SetupWizardWindow.IsCliVersionMatched` to use `CliVersionComparison.IsSameVersion`

### Tool Settings & Skill Installation
- **tool-settings-loader.ts**: 
  - Refactored to resolve Unity project root via `resolveProjectRoot(...)` helper
  - Added `shouldBypassDisabledSettingForDependencyError()` to conditionally treat `run-tests` as enabled when the test framework is not installed
  - `isToolEnabled()` and `filterEnabledTools()` now apply framework-availability bypass for `run-tests`
  
- **ToolSkillSynchronizer.cs**: 
  - Added `IsSkillDisabledByToolSettings()` predicate incorporating test framework availability
  - Modified skill installation to gate disablement on `ShouldReportDependencyUnavailableBeforeDisabled()` when framework is unavailable
  
- **skills-manager.ts**: Updated to differentiate tool-disabling—presence in `disabledTools` only triggers removal if `isToolEnabled()` also returns `false`

### Documentation
- **README.md & README_ja.md**: Added explicit note that `com.unity.test-framework` is optional and only required for `run-tests`; documented that `run-tests` returns an unsupported message when the package is missing
- **Packages/src/README.md & README_ja.md**: Updated dependency notes and tool descriptions with same framework-optional messaging
- **SKILL.md**: Updated to state `run-tests` requires the Unity Test Framework and returns `Success: false` with unsupported message when absent

## Test Coverage
- **RunTestsToolTests.cs**: Added assertions on `RunTestsSchema.TestMode` default value and numeric enum mapping; added `CreateTestFrameworkUnavailable_ShouldReturnUnsupportedResponse` test
- **RunTestsUseCaseTests.cs**: Updated stub validation service to use `RunTestMode` parameter
- **TestExecutionStateValidationServiceTests.cs**: Updated all test cases to pass `RunTestMode` values
- **CliVersionComparisonTests.cs** (new): Tests SemVer parsing, optional `v` prefix, pre-release handling, and invalid version detection
- **ToolExecutionAvailabilityTests.cs** (new): Tests dependency unavailability and tool exposure behavior for `run-tests` with and without framework
- **ToolSkillSynchronizerTests.cs**: Added tests for skill disablement based on test framework availability
- **tool-settings-loader.test.ts**: Added test cases for `run-tests` enabling/disabling based on framework package presence in manifests
- **skills-manager.test.ts**: Added integration test for skill installation when test framework is absent
- **package-metadata.test.ts**: Verifies `com.unity.test-framework` is not in distributable package dependencies and `versionDefines` entry exists in editor asmdef

## Impact
- Projects without Unity Test Framework can now successfully install and use uLoop MCP
- The `run-tests` command remains discoverable but returns a clear unsupported/dependency-missing response when the framework is absent
- All other uLoop tools remain functional regardless of Test Framework installation status
- CLI version comparisons now properly handle pre-release versions (e.g., `1.0.0-beta`)

### CODE REVIEW

File: Packages/src/Editor/UI/CliVersionComparison.cs [hunk 1]
```diff
@@ -0,0 +1,208 @@
...
+            if (buildMetadataIndex >= 0)
+            {
+                normalized = normalized.Substring(0, buildMetadataIndex);
+            }
+
+            string preRelease = string.Empty;
+            int preReleaseIndex = normalized.IndexOf('-');
+            if (preReleaseIndex >= 0)
+            {
+                preRelease = normalized.Substring(preReleaseIndex + 1);
```
[the remark this answers is not in the document]
Comment (hatayama) [reply Packages/src/Editor/UI/CliVersionComparison.cs:56]: Fixed in 9472c0eb.

Added prerelease identifier validation before version comparison so malformed versions such as empty identifiers, unsupported characters, and numeric identifiers with leading zeroes fail parsing instead of being compared as valid SemVer.

File: Assets/Tests/Editor/RunTestsToolTests.cs [hunk 2]
```diff
@@ -99,5 +102,19 @@ public void CreateFilter_WithUnsupportedType_ShouldThrowException()
...
+            RunTestsResponse response = RunTestsResponse.CreateTestFrameworkUnavailable();
+
+            Assert.That(response.Success, Is.False);
+            Assert.That(response.Message, Does.Contain("com.unity.test-framework"));
+            Assert.That(response.CompletedAt, Is.Not.Empty);
+            Assert.That(response.TestCount, Is.EqualTo(0));
+            Assert.That(response.PassedCount, Is.EqualTo(0));
+            Assert.That(response.FailedCount, Is.EqualTo(0));
+            Assert.That(response.SkippedCount, Is.EqualTo(0));
+        }
```
[the remark this answers is not in the document]
Comment (hatayama) [reply Assets/Tests/Editor/RunTestsToolTests.cs:130]: Fixed in 9472c0eb.

Added an assertion that the unsupported Test Framework response keeps XmlPath null, matching the runtime contract for no generated XML result.

File: Packages/src/Editor/Api/McpTools/RunTests/RunTestsResponse.cs [hunk 3]
```diff
@@ -73,5 +76,19 @@ public RunTestsResponse()
...
+                success: false,
+                message: TestFrameworkUnavailableMessage,
+                completedAt: DateTime.UtcNow.ToString("o"),
+                testCount: 0,
+                passedCount: 0,
+                failedCount: 0,
+                skippedCount: 0,
+                xmlPath: null
+            );
+        }
```
[the remark this answers is not in the document]
Comment (hatayama) [reply Packages/src/Editor/Api/McpTools/RunTests/RunTestsResponse.cs:92]: Handled in 9472c0eb.

I did not switch the runtime response to an empty string because the current run-tests responses use null when no XML file is generated, including the unsupported Test Framework path. Instead, I updated the source skill documentation to document XmlPath as string | null so clients do not rely on an empty-string contract that the tool does not emit.

File: Packages/src/Cli~/src/tool-settings-loader.ts [hunk 4]
```diff
@@ -57,18 +105,19 @@ export function loadDisabledTools(projectPath?: string): string[] {
...
+function isUnityTestFrameworkInstalled(projectRoot: string): boolean {
+  const manifestPath: string = join(projectRoot, PACKAGES_DIR, MANIFEST_FILE);
+  if (!existsSync(manifestPath)) {
+    return false;
   }
-  return tools.filter((tool) => !disabledTools.includes(tool.name));
+
+  const content: string = readFileSync(manifestPath, 'utf-8');
+  return UNITY_TEST_FRAMEWORK_DEPENDENCY_PATTERN.test(content);
 }
```
[the remark this answers is not in the document]
Comment (hatayama) [reply Packages/src/Cli~/src/tool-settings-loader.ts:136]: Fixed in 9472c0eb.

Added guarded package metadata reads so unreadable manifest or packages-lock files are treated as absent rather than crashing tool availability filtering. The new test covers continuing to packages-lock when manifest.json cannot be read.
